robot_type: single 

data:
  type: teleop
  num_action: 20 
  voxel_size: 0.005 

  sample_traj:
    enable: true
    trans_delta: 0.005
    rot_delta: 0.1309
    width_delta: 0.005

  normalization:
    trans_min: [-0.7, -0.6, 0.3]
    trans_max: [0.7, 0.8, 1.6]
    max_gripper_width: 0.095
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]

  aligner:
    # 这里保持与 RISE2 模板一致，因为这是 Dataloader 预处理图像的尺寸
    img_size_resnet: [360, 640]
    img_size_dinov2: [252, 448]
    img_size_dinov3: [288, 512]
    img_coord_size_resnet: [12, 20]
    img_coord_size_dinov2: [18, 32]
    img_coord_size_dinov3: [18, 32]

  repeat_dataset: 1
  vis: false


train:
  workspace:
    min: [-0.5, -0.4, 0.5] 
    max: [0.5, 0.6, 1.4]

  augmentation:
    point: true
    aug_trans_min: [-0.2, -0.2, -0.2]
    aug_trans_max: [0.2, 0.2, 0.2]
    # aug_rot_min: [-30, -30, -30]
    # aug_rot_max: [30, 30, 30]
    aug_rot_min : [0,0,0]
    aug_rot_max : [0,0,0]

    color: true
    aug_color_params: [0.4, 0.4, 0.2, 0.1]
    aug_color_prob: 0.2
  
  lr: 0.0003
  # batch_size: 240
  batch_size: 200
  # num_workers: 24
  num_workers: 24
  num_steps: 60000
  save_steps: 2500
  num_warmup_steps: 2000
  seed: 233


deploy:
  workspace:
    min: [-0.5, -0.4, 0.5] 
    max: [0.5, 0.6, 1.4]

  agent:
    robot_serial: Rizon4-062077 # 这个地方需要改！
    camera_serial: "104122063550" 
    inhand_camera_serial: "043322070878"
    gripper_port: /dev/ttyUSB0
    gripper_key: width
  
  max_steps: 3000
  num_inference_steps: 20
  gripper_threshold: 0.02
  ensemble_mode: new
  seed: 233
  vis: true


model:
  image_enc: dinov2-base
  cloud_enc_dim: 128
  image_enc_dim: 128
  obs_feature_dim: 512
  hidden_dim: 512
  nheads: 8
  num_attn_layers: 4
  dim_feedforward: 2048
  dropout: 0.1
  interp_fn_mode: custom
  image_enc_finetune: full
  image_enc_dtype: float32
